version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - ./dbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
    networks:
      - app-network


  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mongo
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - ./storage:/app/storage
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge